### PR TITLE
Refactor again and add javadoc

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
1. add javadoc to the methods in CFGVisualizer and Store.
2. add javadoc to explain the unchecked cast in visualize() of CFAbstractStore
3. extract visualizeBlock() visualizeSpecialBlock() visualizeBlockTransferInput() and visualizeBlockNode() to CFGVisualizer as part of the interface.
4. Change sbDigraph from local var to a field of DOTCFGVisualizer as a shared StringBuilder among the visualise methods.
5. Add field sbBlock in DOTCFGVisualizer as a shared StringBuilder among the visualize Block methods.
   5.Fix indentation issues.

### CODE REVIEW

**Comment by wmdietl** [comment]
Thanks! I've made a few final fixes and merged this (finally...).

**Comment by CharlesZ-Chen** [comment]
Thanks a lot! indeed it takes a long time... Next time will try to do better!

**Comment by wmdietl** [comment]
Pull request against trunk is here:
https://github.com/typetools/checker-framework/pull/662
Was entirely my fault for not looking at your pull request sooner.

**Comment by CharlesZ-Chen** [comment]
Got it. I've starred and watched typetools on github, thus already seen it. Thanks for the improvement on documentation! Learns some things from it for writing better documentations.

**Pull request merged**
